apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "labs-timja-frontend-test"
  description: "hello"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_labs/labs-timja-test
    github.com/project-slug: 'hmcts-test/labs-timja-test'
  tags:
    - nodejs
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: labs
  lifecycle: experimental
  owner: dts_platform_operations
